name: Build, Test and Publish Pyinstaller Binaries

on:
  push:
    branches:
      - winget

env:
  production_release: "false"
  python_version: "3.12"

jobs:
  build-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-14 is the Apple Silicon M1 runner
        os: [ubuntu-20.04, windows-2019, macos-latest]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.production_release == 'true' && '0' || '1' }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}

      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Build & test binary
        uses: ./.github/actions/build-binaries
        with:
          python_version: ${{ env.python_version }}
          package_name: "algokit"
          production_release: ${{ env.production_release }}
          operating_system: ${{ runner.os }}
          architecture: ${{ runner.arch }}
