name: Codebase validation

on:
  push:
    branches:
      - winget-cd-test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    name: Check Python
    uses: ./.github/workflows/check-python.yaml

  pr-build:
    name: Build & Test Python
    needs: pr-check
    uses: ./.github/workflows/build-python.yaml

  pr-binaries-build:
    name: Build & Test Binaries
    needs: pr-check
    uses: ./.github/workflows/build-binaries.yaml
    with:
      production_release: "false"
      python_version: "3.12"
    secrets: inherit

  cd-publish-release-packages:
    name: Release binaries via distribution channels
    needs:
      - pr-binaries-build
    uses: ./.github/workflows/publish-release-packages.yaml
    with:
      artifactName: algokit-cli
      release_version: "2.2.2"
    secrets: inherit
