name: Publish packages to public repositories

on:
  workflow_call:
    inputs:
      artifactName:
        required: true
        type: string
        description: "The github artifact holding the wheel file which will be published"
      release_version:
        required: true
        type: string
        description: "The release version that will be published (e.g. 0.1.0)"
      do_brew:
        required: false
        default: true
        type: boolean
        description: "Publish to brew repository"
      do_chocolatey:
        required: false
        default: true
        type: boolean
        description: "Publish to Chocolatey repository"
      do_snap:
        required: false
        default: true
        type: boolean
        description: "Publish to snap repository"
      do_winget:
        required: false
        default: true
        type: boolean
        description: "Publish to Winget repository"
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        type: string
        description: "The release version that will be published (e.g. 0.1.0). Note this is not the tag version."
      do_brew:
        required: false
        default: true
        type: boolean
        description: "Publish to brew repository"
      do_chocolatey:
        required: false
        default: true
        type: boolean
        description: "Publish to Chocolatey repository"
      do_winget:
        required: false
        default: true
        type: boolean
        description: "Publish to Winget repository"
      do_snap:
        required: false
        default: true
        type: boolean
        description: "Publish to snap repository"

jobs:
  publish-winget:
    runs-on: windows-latest
    if: ${{ inputs.do_winget }}
    steps:
      - name: Publish to winget
        shell: pwsh
        env:
          WINGET_GITHUB_TOKEN: "TESTING"
        run: |
          echo 'Publishing to winget'
          & .\scripts\winget\update-package.ps1 `
            -releaseVersion '${{ inputs.release_version }}'
